/*
  View: VW_TITULOS_ABERTO_COMPRADOR
  Autor: Carlos Nascimento
   Descrição:
    View para análise de títulos em aberto por comprador. Consolida 
    informações de títulos financeiros, programação de pagamentos e 
    compradores, aplicando regras de negócio para associação de despesas
    e cálculo de métricas de pagamento.
  Principais funcionalidades:
    - Identifica o comprador responsável por cada título
    - Calcula dias de pagamento com regras específicas por tipo
    - Agrupa informações de parcelas e títulos originais
    - Filtra títulos em aberto excluindo cancelados

----------------- VIEW ADAPTADA PARA OCULTAR INFORMAÇÕES SENSIVEIS 
  Data de criação: 2024
*/

CREATE OR REPLACE VIEW VW_TITULOS_ABERTO_COMPRADOR AS
SELECT "RN",
       "COMPRADOR",
       "COD_ESPECIE",
       "TITULO",
       "FILIAL",
       "SEQ_PESSOA",
       "FORNECEDOR",
       "DTA_INCLUSAO",
       "DTA_INCLUSAO_PGTO",
       "DTA_INCLUSAO_FMT",
       "DTA_PROGRAMADA",
       "DTA_PROGRAMADA_FMT",
       "VLR_ORIGINAL",
       "JUROS_MULTA",
       "EMPRESA",
       "DTA_HORA_ALTERACAO",
       "DTA_HORA_ALTERACAO_FMT",
       "EXC_ESPECIES",
       "STATUS",
       "DTA_EMISSAO",
       "DTA_EMISSAO_FMT",
       "DIAS_PAGAMENTO",
       "NOME_REDUZIDO_EMPRESA",
       "CONTA_CORRENTE",
       "TIPO_PAGTO",
       "FORMA_PAGAMENTO",
       "MEDIA_GERAL_DIAS",
       "DATA_INCL_PROG",
       "HISTORICO"
FROM (
    SELECT
    T0.SEQ_TITULO,
        ROW_NUMBER() OVER (PARTITION BY T0.SEQ_TITULO
                           ORDER BY T3.COMPRADOR,
                                    T1.COD_ESPECIE,
                                    T0.DTA_PROGRAMACAO,
                                    T4.NOME_RAZAO,
                                    T1.NRO_TITULO || T1.NRO_PARCELA) AS RN,

NVL(
    T3.COMPRADOR,
    CASE
        -- Caso FRETE: busca comprador pelos titulos do mesmo NRO_PROCESSO
        WHEN T1.COD_ESPECIE = 'FRETE' THEN NVL((
            SELECT MAX(C_SUB.COMPRADOR)
            FROM FIN_TITULO_OPERACAO OP_SUB
            JOIN FIN_TITULO_COMPRADOR TC_SUB
                ON TC_SUB.SEQ_TITULO = OP_SUB.SEQ_TITULO
            JOIN DIM_COMPRADOR C_SUB
                ON C_SUB.SEQ_COMPRADOR = TC_SUB.SEQ_COMPRADOR
            WHERE OP_SUB.NRO_PROCESSO = (
                SELECT OP.NRO_PROCESSO
                FROM FIN_TITULO_OPERACAO OP
                WHERE OP.SEQ_TITULO = T1.SEQ_TITULO
                  AND ROWNUM = 1
            )
            AND OP_SUB.SEQ_TITULO != T1.SEQ_TITULO
        ), '*DESPESA*')

        -- Caso seja uma parcela sem comprador: busca o titulo original
        WHEN EXISTS (
            SELECT 1
            FROM FIN_TITULO T_ORIG
            WHERE T_ORIG.NRO_TITULO  = T1.NRO_TITULO
              AND T_ORIG.NRO_EMPRESA = T1.NRO_EMPRESA
              AND T_ORIG.SEQ_PESSOA  = T1.SEQ_PESSOA
              AND T_ORIG.SITUACAO   = ''
              AND T_ORIG.ORIGEM_DOC  = ''
              AND T_ORIG.SEQ_TITULO <> T1.SEQ_TITULO
        )
        AND NOT EXISTS (
            SELECT 1
            FROM FIN_TITULO_COMPRADOR TC
            WHERE TC.SEQ_TITULO = T1.SEQ_TITULO
        ) THEN NVL((
            SELECT MAX(C_SUB.COMPRADOR)
            FROM (
                SELECT TIT_ORIG.SEQ_TITULO
                FROM FIN_TITULO TIT_ORIG
                WHERE TIT_ORIG.NRO_TITULO  = T1.NRO_TITULO
                  AND TIT_ORIG.NRO_EMPRESA = T1.NRO_EMPRESA
                  AND TIT_ORIG.SEQ_PESSOA  = T1.SEQ_PESSOA
                  AND TIT_ORIG.SITUACAO   = ''
                  AND TIT_ORIG.ORIGEM_DOC  = ''
                  AND TIT_ORIG.SEQ_TITULO <> T1.SEQ_TITULO
                  AND TIT_ORIG.NRO_PARCELA = (
                      SELECT MIN(T2.NRO_PARCELA)
                      FROM FIN_TITULO T2
                      WHERE T2.NRO_TITULO  = T1.NRO_TITULO
                        AND T2.NRO_EMPRESA = T1.NRO_EMPRESA
                        AND T2.SEQ_PESSOA  = T1.SEQ_PESSOA
                        AND T2.SITUACAO   = ''
                        AND T2.ORIGEM_DOC  = ''
                  )
            ) TIT_SEL
            JOIN FIN_TITULO_COMPRADOR TC_SUB
                ON TC_SUB.SEQ_TITULO = TIT_SEL.SEQ_TITULO
            JOIN DIM_COMPRADOR C_SUB
                ON C_SUB.SEQ_COMPRADOR = TC_SUB.SEQ_COMPRADOR
        ), '*DESPESA*')

        -- Fallback
        ELSE '*DESPESA*'
    END
) AS COMPRADOR,
        T1.COD_ESPECIE || ' - ' || T5.DESCRICAO COD_ESPECIE,
        T1.NRO_TITULO || ' - Parc: ' || T1.NRO_PARCELA TITULO,
        T1.NRO_EMPRESA AS FILIAL,
        T4.SEQ_PESSOA,
        T4.NOME_RAZAO FORNECEDOR,
        T1.DTA_INCLUSAO,
        T0.DTA_INCLUSAO AS DTA_INCLUSAO_PGTO,
        TO_CHAR(T1.DTA_INCLUSAO, 'DD/MM/YYYY') DTA_INCLUSAO_FMT,
        T0.DTA_PROGRAMACAO DTA_PROGRAMADA,
        TO_CHAR(T0.DTA_PROGRAMACAO, 'DD/MM/YYYY') DTA_PROGRAMADA_FMT,
        T0.VLR_PAGAR AS VLR_ORIGINAL,
        T0.VLR_JUROS + T0.VLR_MULTA AS JUROS_MULTA,

        CASE
            WHEN T1.NRO_EMPRESA IN (1, 2, 3, 4) THEN 'EMPRESA_A'
            WHEN T1.NRO_EMPRESA IN (5) THEN 'EMPRESA_B'
            ELSE 'EMPRESA_C'
        END EMPRESA,

        T0.DTA_HORA_ALTERACAO DTA_HORA_ALTERACAO,
        TO_CHAR(T0.DTA_HORA_ALTERACAO, 'DD/MM/YYYY HH24:MI') DTA_HORA_ALTERACAO_FMT,
        CASE
            WHEN T1.COD_ESPECIE IN ('ESP01', 'ESP02', 'ESP03', 'ESP04', 'ESP05') THEN '0'
            ELSE '1'
        END EXC_ESPECIES,
        T1.ABERTO_QUITADO AS STATUS,
        T1.DTA_EMISSAO,
        TO_CHAR(T1.DTA_EMISSAO, 'DD/MM/YYYY') DTA_EMISSAO_FMT,

CASE
    -- Calculo especifico para impostos e taxas
    WHEN T1.COD_ESPECIE IN ('IMP01','IMP02','IMP03','IMP04','IMP05','IMP06','IMP07','IMP08','IMP09','IMP10','IMP11','IMP12') THEN
        ABS(TRUNC(T0.DTA_PROGRAMACAO) - TRUNC(T1.DTA_EMISSAO))

    -- Parcelados 
    WHEN T1.QTD_PARCELA > 1 AND T1.ORIGEM_DOC = 'INTE' THEN
        ABS(TRUNC(T0.DTA_PROGRAMACAO) - TRUNC(T1.DTA_EMISSAO))

    -- Media simples dos titulos originais ou fallback
    ELSE
        COALESCE(
            T_MEDIA_ORIG.MEDIA_DIAS_ORIGINAIS,
            ABS(TRUNC(T0.DTA_PROGRAMACAO) - TRUNC(COALESCE(T_ORIG.DTA_EMISSAO_ORIGINAL, T1.DTA_EMISSAO)))
        )
END AS DIAS_PAGAMENTO,

        T6.NOME_REDUZIDO NOME_REDUZIDO_EMPRESA,
        T9.DESCRICAO AS CONTA_CORRENTE,

        CASE
            WHEN T0.FORMA_PAGTO = 'EL' THEN 'Remessa'
            WHEN T0.HISTORICO IS NOT NULL THEN 'Pagamento Manual'
            WHEN T0.FORMA_PAGTO = 'OB' AND T1.COD_ESPECIE IN ('SAL01','SAL02','SAL03','SAL04','SAL05') THEN 'Remessa Folha'
            ELSE 'Aut. Debito em Conta'
        END AS TIPO_PAGTO,

        CASE
            WHEN T0.FORMA_PAGTO = 'EL' THEN 'Eletronico'
            WHEN T0.FORMA_PAGTO = 'OB' THEN 'Aut. Debito em Conta'
            WHEN T0.FORMA_PAGTO = 'DI' THEN 'Dinheiro'
            WHEN T0.FORMA_PAGTO = 'CP' THEN 'Cheque Proprio'
        END AS FORMA_PAGAMENTO,

        ROUND(AVG(ABS(T0.DTA_PROGRAMACAO - T1.DTA_EMISSAO)) OVER ()) AS MEDIA_GERAL_DIAS,
        T0.DTA_INCLUSAO AS DATA_INCL_PROG,
        CASE
            WHEN T0.FORMA_PAGTO = 'OB' AND T1.APP_ORIGEM <> '' AND T1.NRO_AUT_ELETRONICA IS NOT NULL THEN NULL
            WHEN T0.FORMA_PAGTO = 'OB' AND T1.APP_ORIGEM = '' AND T1.NRO_AUT_ELETRONICA IS NULL THEN NVL(T0.HISTORICO, T1.NRO_TITULO || ' - ' || T1.NRO_EMPRESA)
            WHEN T0.FORMA_PAGTO = 'OB' AND T1.APP_ORIGEM IS NULL AND T1.NRO_AUT_ELETRONICA IS NULL THEN NVL(T0.HISTORICO, T1.NRO_TITULO || ' - ' || T1.NRO_EMPRESA)
            WHEN T0.FORMA_PAGTO = 'EL' THEN NULL
            ELSE NULL
        END AS HISTORICO

    FROM
        FIN_PROG_PAGAMENTO T0
        INNER JOIN FIN_TITULO T1 ON T1.SEQ_TITULO = T0.SEQ_TITULO
        LEFT JOIN (
    SELECT TC_FILTRADO.SEQ_TITULO, C.COMPRADOR
    FROM (
        SELECT
            TC.SEQ_TITULO,
            TC.SEQ_COMPRADOR,
            T.VLR_ORIGINAL,
            TC.VALOR,
            ROW_NUMBER() OVER (
                PARTITION BY TC.SEQ_TITULO
                ORDER BY
                    CASE WHEN TC.VALOR = T.VLR_ORIGINAL THEN 0 ELSE 1 END,
                    TC.VALOR DESC
            ) AS RN
        FROM FIN_TITULO_COMPRADOR TC
        JOIN FIN_TITULO T ON T.SEQ_TITULO = TC.SEQ_TITULO
    ) TC_FILTRADO
    JOIN DIM_COMPRADOR C ON C.SEQ_COMPRADOR = TC_FILTRADO.SEQ_COMPRADOR
    WHERE TC_FILTRADO.RN = 1
) T3 ON T3.SEQ_TITULO = T1.SEQ_TITULO

LEFT JOIN (
    SELECT
        NRO_TITULO, NRO_EMPRESA, COD_ESPECIE, SEQ_PESSOA,
        MIN(DTA_EMISSAO) AS DTA_EMISSAO_ORIGINAL
    FROM FIN_TITULO
    WHERE ORIGEM_DOC = 'INTE'
    GROUP BY NRO_TITULO, NRO_EMPRESA, COD_ESPECIE, SEQ_PESSOA
) T_ORIG ON T_ORIG.NRO_TITULO = T1.NRO_TITULO
        AND T_ORIG.NRO_EMPRESA = T1.NRO_EMPRESA
        AND T_ORIG.COD_ESPECIE = T1.COD_ESPECIE
        AND T_ORIG.SEQ_PESSOA = T1.SEQ_PESSOA

LEFT JOIN (
    SELECT
        T_AGR.NRO_TITULO,
        T_AGR.NRO_EMPRESA,
        T_AGR.SEQ_PESSOA,
        T_AGR.COD_ESPECIE,
        AVG(ABS(PP.DTA_PROGRAMACAO - COALESCE(T_ORIG_SUB.DTA_EMISSAO_ORIGINAL, T_ORIG_SIMPLE.DTA_EMISSAO))) AS MEDIA_DIAS_ORIGINAIS
    FROM FIN_TITULO T_AGR
    INNER JOIN FIN_TITULO T_ORIG_SIMPLE ON
        T_ORIG_SIMPLE.NRO_TITULO = T_AGR.NRO_TITULO
        AND T_ORIG_SIMPLE.NRO_EMPRESA = T_AGR.NRO_EMPRESA
        AND T_ORIG_SIMPLE.SEQ_PESSOA = T_AGR.SEQ_PESSOA
        AND T_ORIG_SIMPLE.ORIGEM_DOC = 'INTE'
        AND T_ORIG_SIMPLE.SITUACAO = 'X'
        AND T_ORIG_SIMPLE.COD_ESPECIE = T_AGR.COD_ESPECIE
        AND T_ORIG_SIMPLE.SEQ_TITULO <> T_AGR.SEQ_TITULO
        AND (T_ORIG_SIMPLE.QTD_PARCELA IS NULL OR T_ORIG_SIMPLE.QTD_PARCELA <= 1)  
    LEFT JOIN FIN_PROG_PAGAMENTO PP ON PP.SEQ_TITULO = T_ORIG_SIMPLE.SEQ_TITULO
    LEFT JOIN (
        SELECT
            NRO_TITULO, NRO_EMPRESA, COD_ESPECIE, SEQ_PESSOA,
            MIN(DTA_EMISSAO) AS DTA_EMISSAO_ORIGINAL
        FROM FIN_TITULO
        WHERE ORIGEM_DOC = 'INTE'
        GROUP BY NRO_TITULO, NRO_EMPRESA, COD_ESPECIE, SEQ_PESSOA
    ) T_ORIG_SUB ON
        T_ORIG_SUB.NRO_TITULO = T_ORIG_SIMPLE.NRO_TITULO
        AND T_ORIG_SUB.NRO_EMPRESA = T_ORIG_SIMPLE.NRO_EMPRESA
        AND T_ORIG_SUB.COD_ESPECIE = T_ORIG_SIMPLE.COD_ESPECIE
        AND T_ORIG_SUB.SEQ_PESSOA = T_ORIG_SIMPLE.SEQ_PESSOA
    WHERE T_AGR.SITUACAO <> 'C'
    GROUP BY T_AGR.NRO_TITULO, T_AGR.NRO_EMPRESA, T_AGR.COD_ESPECIE, T_AGR.SEQ_PESSOA
) T_MEDIA_ORIG ON
    T_MEDIA_ORIG.NRO_TITULO = T1.NRO_TITULO
    AND T_MEDIA_ORIG.NRO_EMPRESA = T1.NRO_EMPRESA
    AND T_MEDIA_ORIG.SEQ_PESSOA = T1.SEQ_PESSOA
    AND T_MEDIA_ORIG.COD_ESPECIE = T1.COD_ESPECIE

        INNER JOIN DIM_PESSOA T4 ON T4.SEQ_PESSOA = T1.SEQ_PESSOA
        LEFT JOIN FIN_ESPECIE T5 ON T5.COD_ESPECIE = T1.COD_ESPECIE AND T1.NRO_EMPRESA_MAE = T5.NRO_EMPRESA_MAE
        INNER JOIN DIM_EMPRESA T6 ON T6.NRO_EMPRESA = T1.NRO_EMPRESA
        INNER JOIN FIN_CTA_CORRENTE T9 ON T9.SEQ_CTA_CORRENTE = T0.SEQ_CTA_CORRENTE
        INNER JOIN FIN_COMPL_TITULO T8 ON T8.SEQ_TITULO = T0.SEQ_TITULO

    WHERE
        T1.OBRIG_DIREITO = 'O'
        AND T1.SITUACAO <> 'C'
        AND T1.DTA_EMISSAO > TO_DATE('01-JAN-2020', 'DD-MON-YYYY')
        AND (T0.SITUACAO <> 'C' OR T0.SITUACAO IS NULL)
        AND T0.SEQ_CTA_CORRENTE IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)
)
WHERE RN = 1
ORDER BY
    CASE
        WHEN COMPRADOR = '*DESPESA*' THEN 'ZZZZZZZZZZ'
        ELSE COMPRADOR
    END,
    COD_ESPECIE,
    DTA_PROGRAMADA,
    FORNECEDOR,
    TITULO
;

