/*
  View: PASV_TITULOS_EM_ABERTO_COMPRADOR_DEV
  Autor: Carlos Ribeiro
  Descrição: Versão refatorada da view anterior, estruturada com CTEs (WITH),
              melhor legibilidade, performance e manutenção.
  Principais melhorias:
  - Separação lógica em CTEs nomeadas
  - Eliminação de subqueries redundantes
  - Padronização de aliases e campos
  - Inclusão de comentários explicativos
  - Clareza na identificação do comprador final e origem do título

  Data de refatoração: 2025
*/


CREATE OR REPLACE VIEW PASV_TITULOS_EM_ABERTO_COMPRADOR_DEV AS
WITH

-- Filtro de dados simples necessario para o relatorio 
DADOS_FILTRADOS AS (
    SELECT
        T0.SEQTITULO,
        T0.DTAPROGRAMACAO,
        T0.DTAINCLUSAO,
        T0.VLRPAGAR,
        T0.VLRJUROS,
        T0.VLRMULTA,
        T0.DTAHORALTERACAO,
        T0.FORMAPAGTO,
        T0.HISTORICO,
        T0.SEQCTACORRENTE,
        T1.NROTITULO,
        T1.NROPARCELA,
        T1.CODESPECIE,
        T1.NROEMPRESA,
        T1.SEQPESSOA,
        T1.DTAINCLUSAO AS DTAINCLUSAOTIT,
        T1.DTAEMISSAO,
        T1.ABERTOQUITADO,
        T1.QTDPARCELA,
        T1.ORIGEMDOC,
        T1.SITUACAO,
        T1.APPORIGEM,
        T1.NROAUTELETRONICA,
        T1.NROEMPRESAMAE,
        T1.VLRORIGINAL AS VLRORIGINALTIT
    FROM FI_PROGPAGAMENTO T0
    INNER JOIN FI_TITULO T1 ON T1.SEQTITULO = T0.SEQTITULO
    WHERE T1.OBRIGDIREITO = 'O'
        AND T1.SITUACAO <> 'C'
        AND T1.DTAEMISSAO > TO_DATE('01-JAN-2020', 'DD-MON-YYYY')
        AND (T0.SITUACAO <> 'C' OR T0.SITUACAO IS NULL)
        AND T0.SEQCTACORRENTE IN (30735,31, 21779, 30215, 30216, 8545, 35903, 30368, 25142, 22169,31815,28522 ,663, 25, 24, 23, 28, 12863, 42, 221, 33116, 33118, 30367, 28495, 30218, 27, 32)
),

/* ---------------------------------------------------------------------------------------------------------------------------- */
/* ---------------------------------------------------------------------------------------------------------------------------- */
/* ------------------------------------------------ CTes com regras do negocio ------------------------------------------------ */
/* ---------------------------------------------------------------------------------------------------------------------------- */
/* ---------------------------------------------------------------------------------------------------------------------------- */

-- Regra de negocio para buscar a data de emissao original do pedido
EMISSAO_ORIGINAL AS (
    SELECT
        NROTITULO, NROEMPRESA, CODESPECIE, SEQPESSOA,
        MIN(DTAEMISSAO) AS DTAEMISSAO_ORIGINAL
    FROM FI_TITULO
    WHERE ORIGEMDOC = 'INTE'
        AND NROTITULO IN (SELECT DISTINCT NROTITULO FROM DADOS_FILTRADOS)
    GROUP BY NROTITULO, NROEMPRESA, CODESPECIE, SEQPESSOA
),

-- Regra de negocio para calcular o prazo medio de pagamento do titulo original 
MEDIA_DIAS_ORIGINAIS AS (
    SELECT
        T_AGR.NROTITULO,
        T_AGR.NROEMPRESA,
        T_AGR.SEQPESSOA,
        T_AGR.CODESPECIE,
        AVG(ABS(PP.DTAPROGRAMACAO - COALESCE(EO.DTAEMISSAO_ORIGINAL, T_ORIG.DTAEMISSAO))) AS MEDIA_DIAS_ORIGINAIS
    FROM DADOS_FILTRADOS T_AGR
    INNER JOIN FI_TITULO T_ORIG ON
        T_ORIG.NROTITULO = T_AGR.NROTITULO
        AND T_ORIG.NROEMPRESA = T_AGR.NROEMPRESA
        AND T_ORIG.SEQPESSOA = T_AGR.SEQPESSOA
        AND T_ORIG.ORIGEMDOC = 'INTE'
        AND T_ORIG.SITUACAO = 'X'
        AND T_ORIG.CODESPECIE = T_AGR.CODESPECIE
        AND T_ORIG.SEQTITULO <> T_AGR.SEQTITULO
        AND (T_ORIG.QTDPARCELA IS NULL OR T_ORIG.QTDPARCELA <= 1)
    LEFT JOIN FI_PROGPAGAMENTO PP ON PP.SEQTITULO = T_ORIG.SEQTITULO
    LEFT JOIN EMISSAO_ORIGINAL EO ON
        EO.NROTITULO = T_ORIG.NROTITULO
        AND EO.NROEMPRESA = T_ORIG.NROEMPRESA
        AND EO.CODESPECIE = T_ORIG.CODESPECIE
        AND EO.SEQPESSOA = T_ORIG.SEQPESSOA
    GROUP BY T_AGR.NROTITULO, T_AGR.NROEMPRESA, T_AGR.CODESPECIE, T_AGR.SEQPESSOA
),

-- Identificar o comprador original do titulo
-- Devido ao processo realizado pelo financeiro para pagamento, alguns titulos se perdem na tabela de comprador
COMPRADOR_PRINCIPAL AS (
    SELECT
        TC_FILTRADO.SEQTITULO,
        C.COMPRADOR
    FROM (
        SELECT
            TC.SEQTITULO,
            TC.SEQCOMPRADOR,
            TC.VALOR,
            DF.VLRORIGINALTIT,
            ROW_NUMBER() OVER (
                PARTITION BY TC.SEQTITULO
                ORDER BY
                    CASE WHEN TC.VALOR = DF.VLRORIGINALTIT THEN 0 ELSE 1 END,
                    TC.VALOR DESC
            ) AS RN
        FROM FI_TITCOMPRADOR TC
        INNER JOIN DADOS_FILTRADOS DF ON DF.SEQTITULO = TC.SEQTITULO
    ) TC_FILTRADO
    INNER JOIN MAX_COMPRADOR C ON C.SEQCOMPRADOR = TC_FILTRADO.SEQCOMPRADOR
    WHERE TC_FILTRADO.RN = 1
),


-- Calcular comprador para FRETE
-- Quando e frete, o departamento financeiro unifica todos os titulos da tranportadora em um titulo unico, por isso e necessario achar o 'comprador' original daquele titulo
COMPRADOR_FRETE AS (
    SELECT DISTINCT
        DF.SEQTITULO,
        COALESCE(MAX(C_SUB.COMPRADOR) OVER (PARTITION BY DF.SEQTITULO), '*DESPESA*') AS COMPRADOR
    FROM DADOS_FILTRADOS DF
    INNER JOIN FI_TITOPERACAO OP ON OP.SEQTITULO = DF.SEQTITULO
    LEFT JOIN FI_TITOPERACAO OP_SUB ON OP_SUB.NROPROCESSO = OP.NROPROCESSO AND OP_SUB.SEQTITULO != DF.SEQTITULO
    LEFT JOIN FI_TITCOMPRADOR TC_SUB ON TC_SUB.SEQTITULO = OP_SUB.SEQTITULO
    LEFT JOIN MAX_COMPRADOR C_SUB ON C_SUB.SEQCOMPRADOR = TC_SUB.SEQCOMPRADOR
    WHERE DF.CODESPECIE = 'FRETE'
),

-- Calcular comprador para parcelas sem comprador
-- identifica qual e a parcela que originou o titulo que foi agragado pelo financeiro
MENOR_PARCELA AS (
    SELECT
        NROTITULO,
        NROEMPRESA,
        SEQPESSOA,
        MIN(NROPARCELA) AS MIN_PARCELA
    FROM FI_TITULO
    WHERE SITUACAO = 'X'
        AND ORIGEMDOC = 'INTE'
    GROUP BY NROTITULO, NROEMPRESA, SEQPESSOA
),

-- identifica o comprador da parcela que originou o titulo agregado, utilizando algumas condicoes estabelecidas pela regra do negocio
COMPRADOR_PARCELA AS (
    SELECT
        DF.SEQTITULO,
        COALESCE(MAX(C_SUB.COMPRADOR), '*DESPESA*') AS COMPRADOR
    FROM DADOS_FILTRADOS DF
    LEFT JOIN MENOR_PARCELA MP ON
        MP.NROTITULO = DF.NROTITULO
        AND MP.NROEMPRESA = DF.NROEMPRESA
        AND MP.SEQPESSOA = DF.SEQPESSOA
    LEFT JOIN FI_TITULO TIT_ORIG ON
        TIT_ORIG.NROTITULO = DF.NROTITULO
        AND TIT_ORIG.NROEMPRESA = DF.NROEMPRESA
        AND TIT_ORIG.SEQPESSOA = DF.SEQPESSOA
        AND TIT_ORIG.SITUACAO = 'X'
        AND TIT_ORIG.ORIGEMDOC = 'INTE'
        AND TIT_ORIG.SEQTITULO <> DF.SEQTITULO
        AND TIT_ORIG.NROPARCELA = MP.MIN_PARCELA
    LEFT JOIN FI_TITCOMPRADOR TC_SUB ON TC_SUB.SEQTITULO = TIT_ORIG.SEQTITULO
    LEFT JOIN MAX_COMPRADOR C_SUB ON C_SUB.SEQCOMPRADOR = TC_SUB.SEQCOMPRADOR
    WHERE EXISTS (
        SELECT 1
        FROM FI_TITULO T_ORIG
        WHERE T_ORIG.NROTITULO = DF.NROTITULO
            AND T_ORIG.NROEMPRESA = DF.NROEMPRESA
            AND T_ORIG.SEQPESSOA = DF.SEQPESSOA
            AND T_ORIG.SITUACAO = 'X'
            AND T_ORIG.ORIGEMDOC = 'INTE'
            AND T_ORIG.SEQTITULO <> DF.SEQTITULO
    )
    AND NOT EXISTS (
        SELECT 1
        FROM FI_TITCOMPRADOR TC
        WHERE TC.SEQTITULO = DF.SEQTITULO
    )
    GROUP BY DF.SEQTITULO
),

-- Retorna o comprador final do titulo considerando as identificacoes para a regra de negocio
COMPRADOR_FINAL AS (
    SELECT
        DF.SEQTITULO,
        COALESCE(
            CP.COMPRADOR,
            CF.COMPRADOR,
            CPA.COMPRADOR,
            '*DESPESA*'
        ) AS COMPRADOR
    FROM DADOS_FILTRADOS DF
    LEFT JOIN COMPRADOR_PRINCIPAL CP ON CP.SEQTITULO = DF.SEQTITULO
    LEFT JOIN COMPRADOR_FRETE CF ON CF.SEQTITULO = DF.SEQTITULO
    LEFT JOIN COMPRADOR_PARCELA CPA ON CPA.SEQTITULO = DF.SEQTITULO
),

-- Query principal com ROW_NUMBER aplicado apos filtros, necessario para identificar se o titulo e considerado 'extra' ou 'programado'
-- Cria uma chave unica que liga com as tabelas principais do sistema
DADOS_ENRIQUECIDOS AS (
    SELECT
        DF.*,
        CFINAL.COMPRADOR,
        T4.NOMERAZAO AS FORNECEDOR,
        T5.DESCRICAO AS DESCRICAO_ESPECIE,
        T6.NOMEREDUZIDO AS NOMEREDUZIDO_EMPRESA,
        T8.SEQTITULO AS SEQTITULO_COMPL,
        T9.DESCRICAO AS CONTA_CORRENTE,
        EO.DTAEMISSAO_ORIGINAL,
        MDO.MEDIA_DIAS_ORIGINAIS,
        ROW_NUMBER() OVER (
            PARTITION BY DF.SEQTITULO
            ORDER BY CFINAL.COMPRADOR,
                     DF.CODESPECIE,
                     DF.DTAPROGRAMACAO,
                     T4.NOMERAZAO,
                     DF.NROTITULO || DF.NROPARCELA
        ) AS RN
    FROM DADOS_FILTRADOS DF
    INNER JOIN COMPRADOR_FINAL CFINAL ON CFINAL.SEQTITULO = DF.SEQTITULO
    INNER JOIN GE_PESSOA T4 ON T4.SEQPESSOA = DF.SEQPESSOA
    INNER JOIN MAX_EMPRESA T6 ON T6.NROEMPRESA = DF.NROEMPRESA
    INNER JOIN FI_CTACORRENTE T9 ON T9.SEQCTACORRENTE = DF.SEQCTACORRENTE
    INNER JOIN FI_COMPLTITULO T8 ON T8.SEQTITULO = DF.SEQTITULO
    LEFT JOIN FI_ESPECIE T5 ON T5.CODESPECIE = DF.CODESPECIE AND DF.NROEMPRESAMAE = T5.NROEMPRESAMAE
    LEFT JOIN EMISSAO_ORIGINAL EO ON
        EO.NROTITULO = DF.NROTITULO
        AND EO.NROEMPRESA = DF.NROEMPRESA
        AND EO.CODESPECIE = DF.CODESPECIE
        AND EO.SEQPESSOA = DF.SEQPESSOA
    LEFT JOIN MEDIA_DIAS_ORIGINAIS MDO ON
        MDO.NROTITULO = DF.NROTITULO
        AND MDO.NROEMPRESA = DF.NROEMPRESA
        AND MDO.SEQPESSOA = DF.SEQPESSOA
        AND MDO.CODESPECIE = DF.CODESPECIE
)

-- SELECT final apenas com RN = 1
SELECT
    RN,
    COMPRADOR,
    CODESPECIE || ' - ' || DESCRICAO_ESPECIE AS CODESPECIE,
    NROTITULO || ' - Parc: ' || NROPARCELA AS TITULO,
    NROEMPRESA AS FILIAL,
    SEQPESSOA,
    FORNECEDOR,
    DTAINCLUSAOTIT AS DTAINCLUSAO,
    DTAINCLUSAO AS DTAINCLUSAOPGTO,
    TO_CHAR(DTAINCLUSAOTIT, 'DD/MM/YYYY') AS DTAINCLUSAOFMT,
    DTAPROGRAMACAO AS DTAPROGRAMADA,
    TO_CHAR(DTAPROGRAMACAO, 'DD/MM/YYYY') AS DTAPROGRAMADAFMT,
    VLRPAGAR AS VLRORIGINAL,
    VLRJUROS + VLRMULTA AS JUROS_MULTA,
    CASE
        WHEN NROEMPRESA IN (30, 31, 32, 33) THEN 'TECH'
        WHEN NROEMPRESA IN (20) THEN 'INSTALA'
        ELSE 'PASSALACQUA'
    END AS EMPRESA,
    DTAHORALTERACAO,
    TO_CHAR(DTAHORALTERACAO, 'DD/MM/YYYY HH24:MI') AS DTAHORAALTERACAOFMT,
    CASE
        WHEN CODESPECIE IN ('DEVPAG', 'NOCRAC', 'NOCRIM', 'NOTACR', 'NOTCRB') THEN '0'
        ELSE '1'
    END AS EXC_ESPECIES,
    ABERTOQUITADO,
    DTAEMISSAO,
    TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') AS DTAEMISSAOFMT,
    CASE
        WHEN CODESPECIE IN ('ISS','IRPJ','ICMSST','IPTU','ICMS','IRSERV','CSLRET','DIFAL','IRAUTO','IRASSA','PROTEG','INSS') THEN
            ABS(TRUNC(DTAPROGRAMACAO) - TRUNC(DTAEMISSAO))
        WHEN QTDPARCELA > 1 AND ORIGEMDOC = 'INTE' THEN
            ABS(TRUNC(DTAPROGRAMACAO) - TRUNC(DTAEMISSAO))
        ELSE
            COALESCE(
                MEDIA_DIAS_ORIGINAIS,
                ABS(TRUNC(DTAPROGRAMACAO) - TRUNC(COALESCE(DTAEMISSAO_ORIGINAL, DTAEMISSAO)))
            )
    END AS DIAS_PAGAMENTO,
    NOMEREDUZIDO_EMPRESA,
    CONTA_CORRENTE,
    CASE
        WHEN FORMAPAGTO = 'EL' THEN 'Remessa'
        WHEN HISTORICO IS NOT NULL THEN 'Pagamento Manual'
        WHEN FORMAPAGTO = 'OB' AND CODESPECIE IN ('ADIFER','ADIRES','ADISAL','ADI13','SALARI') THEN 'Remessa Folha'
        ELSE 'Aut. Debito em Conta'
    END AS TIPO_PAGTO,
    CASE
        WHEN FORMAPAGTO = 'EL' THEN 'Eletronico'
        WHEN FORMAPAGTO = 'OB' THEN 'Aut. Debito em Conta'
        WHEN FORMAPAGTO = 'DI' THEN 'Dinheiro'
        WHEN FORMAPAGTO = 'CP' THEN 'Cheque Proprio'
    END AS FORMA_PAGAMENTO,
    ROUND(AVG(ABS(DTAPROGRAMACAO - DTAEMISSAO)) OVER ()) AS MEDIA_GERAL_DIAS,
    DTAINCLUSAO AS DATAINCLPROG,
    CASE
        WHEN FORMAPAGTO = 'OB' AND APPORIGEM <> 'IntOrcamento' AND NROAUTELETRONICA IS NOT NULL THEN NULL
        WHEN FORMAPAGTO = 'OB' AND APPORIGEM = 'IntOrcamento' AND NROAUTELETRONICA IS NULL THEN NVL(HISTORICO, NROTITULO || ' - ' || NROEMPRESA)
        WHEN FORMAPAGTO = 'OB' AND APPORIGEM IS NULL AND NROAUTELETRONICA IS NULL THEN NVL(HISTORICO, NROTITULO || ' - ' || NROEMPRESA)
        WHEN FORMAPAGTO = 'EL' THEN NULL
        ELSE NULL
    END AS HISTORICO
FROM DADOS_ENRIQUECIDOS
WHERE RN = 1
ORDER BY
    CASE
        WHEN COMPRADOR = '*DESPESA*' THEN 'ZZZZZZZZZZ'
        ELSE COMPRADOR
    END,
    CODESPECIE,
    DTAPROGRAMACAO,
    FORNECEDOR,
    NROTITULO || NROPARCELA
;
