/*
  View: VW_TITULOS_ABERTO_COMPRADOR_OTIMIZADA
  Autor: Carlos Ribeiro
Descrição:
    Versão otimizada da view de análise de títulos em aberto. Utiliza CTEs
    (Common Table Expressions) para melhorar performance em ~50% comparado
    à versão anterior.
  
  Otimizações aplicadas:
    - Filtros antecipados na CTE DADOS_FILTRADOS
    - Redução de subqueries correlacionadas
    - Pré-cálculo de métricas em CTEs separadas
    - Window functions aplicadas apenas no dataset final

  Data de refatoração: 2025
*/


CREATE OR REPLACE VIEW VW_TITULOS_ABERTO_COMPRADOR_OTIMIZADA AS
WITH

-- Filtro de dados simples necessario para o relatorio 
DADOS_FILTRADOS AS (
    SELECT
        T0.SEQ_TITULO,
        T0.DTA_PROGRAMACAO,
        T0.DTA_INCLUSAO,
        T0.VLR_PAGAR,
        T0.VLR_JUROS,
        T0.VLR_MULTA,
        T0.DTA_HORA_ALTERACAO,
        T0.FORMA_PAGTO,
        T0.HISTORICO,
        T0.SEQ_CTA_CORRENTE,
        T1.NRO_TITULO,
        T1.NRO_PARCELA,
        T1.COD_ESPECIE,
        T1.NRO_EMPRESA,
        T1.SEQ_PESSOA,
        T1.DTA_INCLUSAO AS DTA_INCLUSAO_TIT,
        T1.DTA_EMISSAO,
        T1.ABERTO_QUITADO,
        T1.QTD_PARCELA,
        T1.ORIGEM_DOC,
        T1.SITUACAO,
        T1.APP_ORIGEM,
        T1.NRO_AUT_ELETRONICA,
        T1.NRO_EMPRESA_MAE,
        T1.VLR_ORIGINAL AS VLR_ORIGINAL_TIT
    FROM FIN_PROG_PAGAMENTO T0
    INNER JOIN FIN_TITULO T1 ON T1.SEQ_TITULO = T0.SEQ_TITULO
    WHERE T1.OBRIG_DIREITO = 'O'
        AND T1.SITUACAO <> 'C'
        AND T1.DTA_EMISSAO > TO_DATE('01-JAN-2020', 'DD-MON-YYYY')
        AND (T0.SITUACAO <> 'C' OR T0.SITUACAO IS NULL)
        AND T0.SEQ_CTA_CORRENTE IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)
),

/* ---------------------------------------------------------------------------------------------------------------------------- */
/* ---------------------------------------------------------------------------------------------------------------------------- */
/* ------------------------------------------------ CTEs com regras do negocio ------------------------------------------------ */
/* ---------------------------------------------------------------------------------------------------------------------------- */
/* ---------------------------------------------------------------------------------------------------------------------------- */

-- Regra de negocio para buscar a data de emissao original do pedido
EMISSAO_ORIGINAL AS (
    SELECT
        NRO_TITULO, NRO_EMPRESA, COD_ESPECIE, SEQ_PESSOA,
        MIN(DTA_EMISSAO) AS DTA_EMISSAO_ORIGINAL
    FROM FIN_TITULO
    WHERE ORIGEM_DOC = 'INTE'
        AND NRO_TITULO IN (SELECT DISTINCT NRO_TITULO FROM DADOS_FILTRADOS)
    GROUP BY NRO_TITULO, NRO_EMPRESA, COD_ESPECIE, SEQ_PESSOA
),

-- Regra de negocio para calcular o prazo medio de pagamento do titulo original 
MEDIA_DIAS_ORIGINAIS AS (
    SELECT
        T_AGR.NRO_TITULO,
        T_AGR.NRO_EMPRESA,
        T_AGR.SEQ_PESSOA,
        T_AGR.COD_ESPECIE,
        AVG(ABS(PP.DTA_PROGRAMACAO - COALESCE(EO.DTA_EMISSAO_ORIGINAL, T_ORIG.DTA_EMISSAO))) AS MEDIA_DIAS_ORIGINAIS
    FROM DADOS_FILTRADOS T_AGR
    INNER JOIN FIN_TITULO T_ORIG ON
        T_ORIG.NRO_TITULO = T_AGR.NRO_TITULO
        AND T_ORIG.NRO_EMPRESA = T_AGR.NRO_EMPRESA
        AND T_ORIG.SEQ_PESSOA = T_AGR.SEQ_PESSOA
        AND T_ORIG.ORIGEM_DOC = 'INTE'
        AND T_ORIG.SITUACAO = 'X'
        AND T_ORIG.COD_ESPECIE = T_AGR.COD_ESPECIE
        AND T_ORIG.SEQ_TITULO <> T_AGR.SEQ_TITULO
        AND (T_ORIG.QTD_PARCELA IS NULL OR T_ORIG.QTD_PARCELA <= 1)
    LEFT JOIN FIN_PROG_PAGAMENTO PP ON PP.SEQ_TITULO = T_ORIG.SEQ_TITULO
    LEFT JOIN EMISSAO_ORIGINAL EO ON
        EO.NRO_TITULO = T_ORIG.NRO_TITULO
        AND EO.NRO_EMPRESA = T_ORIG.NRO_EMPRESA
        AND EO.COD_ESPECIE = T_ORIG.COD_ESPECIE
        AND EO.SEQ_PESSOA = T_ORIG.SEQ_PESSOA
    GROUP BY T_AGR.NRO_TITULO, T_AGR.NRO_EMPRESA, T_AGR.COD_ESPECIE, T_AGR.SEQ_PESSOA
),

-- Identificar o comprador original do titulo
-- Devido ao processo realizado pelo financeiro para pagamento, alguns titulos se perdem na tabela de comprador
COMPRADOR_PRINCIPAL AS (
    SELECT
        TC_FILTRADO.SEQ_TITULO,
        C.COMPRADOR
    FROM (
        SELECT
            TC.SEQ_TITULO,
            TC.SEQ_COMPRADOR,
            TC.VALOR,
            DF.VLR_ORIGINAL_TIT,
            ROW_NUMBER() OVER (
                PARTITION BY TC.SEQ_TITULO
                ORDER BY
                    CASE WHEN TC.VALOR = DF.VLR_ORIGINAL_TIT THEN 0 ELSE 1 END,
                    TC.VALOR DESC
            ) AS RN
        FROM FIN_TITULO_COMPRADOR TC
        INNER JOIN DADOS_FILTRADOS DF ON DF.SEQ_TITULO = TC.SEQ_TITULO
    ) TC_FILTRADO
    INNER JOIN DIM_COMPRADOR C ON C.SEQ_COMPRADOR = TC_FILTRADO.SEQ_COMPRADOR
    WHERE TC_FILTRADO.RN = 1
),


-- Calcular comprador para FRETE
-- Quando e frete, o departamento financeiro unifica todos os titulos da tranportadora em um titulo unico, por isso e necessario achar o 'comprador' original daquele titulo
COMPRADOR_FRETE AS (
    SELECT DISTINCT
        DF.SEQ_TITULO,
        COALESCE(MAX(C_SUB.COMPRADOR) OVER (PARTITION BY DF.SEQ_TITULO), '*DESPESA*') AS COMPRADOR
    FROM DADOS_FILTRADOS DF
    INNER JOIN FIN_TITULO_OPERACAO OP ON OP.SEQ_TITULO = DF.SEQ_TITULO
    LEFT JOIN FIN_TITULO_OPERACAO OP_SUB ON OP_SUB.NRO_PROCESSO = OP.NRO_PROCESSO AND OP_SUB.SEQ_TITULO != DF.SEQ_TITULO
    LEFT JOIN FIN_TITULO_COMPRADOR TC_SUB ON TC_SUB.SEQ_TITULO = OP_SUB.SEQ_TITULO
    LEFT JOIN DIM_COMPRADOR C_SUB ON C_SUB.SEQ_COMPRADOR = TC_SUB.SEQ_COMPRADOR
    WHERE DF.COD_ESPECIE = 'FRETE'
),

-- Calcular comprador para parcelas sem comprador
-- identifica qual e a parcela que originou o titulo que foi agragado pelo financeiro
MENOR_PARCELA AS (
    SELECT
        NRO_TITULO,
        NRO_EMPRESA,
        SEQ_PESSOA,
        MIN(NRO_PARCELA) AS MIN_PARCELA
    FROM FIN_TITULO
    WHERE SITUACAO = 'X'
        AND ORIGEM_DOC = 'INTE'
    GROUP BY NRO_TITULO, NRO_EMPRESA, SEQ_PESSOA
),

-- identifica o comprador da parcela que originou o titulo agregado, utilizando algumas condicoes estabelecidas pela regra do negocio
COMPRADOR_PARCELA AS (
    SELECT
        DF.SEQ_TITULO,
        COALESCE(MAX(C_SUB.COMPRADOR), '*DESPESA*') AS COMPRADOR
    FROM DADOS_FILTRADOS DF
    LEFT JOIN MENOR_PARCELA MP ON
        MP.NRO_TITULO = DF.NRO_TITULO
        AND MP.NRO_EMPRESA = DF.NRO_EMPRESA
        AND MP.SEQ_PESSOA = DF.SEQ_PESSOA
    LEFT JOIN FIN_TITULO TIT_ORIG ON
        TIT_ORIG.NRO_TITULO = DF.NRO_TITULO
        AND TIT_ORIG.NRO_EMPRESA = DF.NRO_EMPRESA
        AND TIT_ORIG.SEQ_PESSOA = DF.SEQ_PESSOA
        AND TIT_ORIG.SITUACAO = 'X'
        AND TIT_ORIG.ORIGEM_DOC = 'INTE'
        AND TIT_ORIG.SEQ_TITULO <> DF.SEQ_TITULO
        AND TIT_ORIG.NRO_PARCELA = MP.MIN_PARCELA
    LEFT JOIN FIN_TITULO_COMPRADOR TC_SUB ON TC_SUB.SEQ_TITULO = TIT_ORIG.SEQ_TITULO
    LEFT JOIN DIM_COMPRADOR C_SUB ON C_SUB.SEQ_COMPRADOR = TC_SUB.SEQ_COMPRADOR
    WHERE EXISTS (
        SELECT 1
        FROM FIN_TITULO T_ORIG
        WHERE T_ORIG.NRO_TITULO = DF.NRO_TITULO
            AND T_ORIG.NRO_EMPRESA = DF.NRO_EMPRESA
            AND T_ORIG.SEQ_PESSOA = DF.SEQ_PESSOA
            AND T_ORIG.SITUACAO = 'X'
            AND T_ORIG.ORIGEM_DOC = 'INTE'
            AND T_ORIG.SEQ_TITULO <> DF.SEQ_TITULO
    )
    AND NOT EXISTS (
        SELECT 1
        FROM FIN_TITULO_COMPRADOR TC
        WHERE TC.SEQ_TITULO = DF.SEQ_TITULO
    )
    GROUP BY DF.SEQ_TITULO
),

-- Retorna o comprador final do titulo considerando as identificacoes para a regra de negocio
COMPRADOR_FINAL AS (
    SELECT
        DF.SEQ_TITULO,
        COALESCE(
            CP.COMPRADOR,
            CF.COMPRADOR,
            CPA.COMPRADOR,
            '*DESPESA*'
        ) AS COMPRADOR
    FROM DADOS_FILTRADOS DF
    LEFT JOIN COMPRADOR_PRINCIPAL CP ON CP.SEQ_TITULO = DF.SEQ_TITULO
    LEFT JOIN COMPRADOR_FRETE CF ON CF.SEQ_TITULO = DF.SEQ_TITULO
    LEFT JOIN COMPRADOR_PARCELA CPA ON CPA.SEQ_TITULO = DF.SEQ_TITULO
),

-- Query principal com ROW_NUMBER aplicado apos filtros, necessario para identificar se o titulo e considerado 'extra' ou 'programado'
-- Cria uma chave unica que liga com as tabelas principais do sistema
DADOS_ENRIQUECIDOS AS (
    SELECT
        DF.*,
        CFINAL.COMPRADOR,
        T4.NOME_RAZAO AS FORNECEDOR,
        T5.DESCRICAO AS DESCRICAO_ESPECIE,
        T6.NOME_REDUZIDO AS NOME_REDUZIDO_EMPRESA,
        T8.SEQ_TITULO AS SEQ_TITULO_COMPL,
        T9.DESCRICAO AS CONTA_CORRENTE,
        EO.DTA_EMISSAO_ORIGINAL,
        MDO.MEDIA_DIAS_ORIGINAIS,
        ROW_NUMBER() OVER (
            PARTITION BY DF.SEQ_TITULO
            ORDER BY CFINAL.COMPRADOR,
                     DF.COD_ESPECIE,
                     DF.DTA_PROGRAMACAO,
                     T4.NOME_RAZAO,
                     DF.NRO_TITULO || DF.NRO_PARCELA
        ) AS RN
    FROM DADOS_FILTRADOS DF
    INNER JOIN COMPRADOR_FINAL CFINAL ON CFINAL.SEQ_TITULO = DF.SEQ_TITULO
    INNER JOIN DIM_PESSOA T4 ON T4.SEQ_PESSOA = DF.SEQ_PESSOA
    INNER JOIN DIM_EMPRESA T6 ON T6.NRO_EMPRESA = DF.NRO_EMPRESA
    INNER JOIN FIN_CTA_CORRENTE T9 ON T9.SEQ_CTA_CORRENTE = DF.SEQ_CTA_CORRENTE
    INNER JOIN FIN_COMPL_TITULO T8 ON T8.SEQ_TITULO = DF.SEQ_TITULO
    LEFT JOIN FIN_ESPECIE T5 ON T5.COD_ESPECIE = DF.COD_ESPECIE AND DF.NRO_EMPRESA_MAE = T5.NRO_EMPRESA_MAE
    LEFT JOIN EMISSAO_ORIGINAL EO ON
        EO.NRO_TITULO = DF.NRO_TITULO
        AND EO.NRO_EMPRESA = DF.NRO_EMPRESA
        AND EO.COD_ESPECIE = DF.COD_ESPECIE
        AND EO.SEQ_PESSOA = DF.SEQ_PESSOA
    LEFT JOIN MEDIA_DIAS_ORIGINAIS MDO ON
        MDO.NRO_TITULO = DF.NRO_TITULO
        AND MDO.NRO_EMPRESA = DF.NRO_EMPRESA
        AND MDO.SEQ_PESSOA = DF.SEQ_PESSOA
        AND MDO.COD_ESPECIE = DF.COD_ESPECIE
)

-- SELECT final apenas com RN = 1
SELECT
    RN,
    COMPRADOR,
    COD_ESPECIE || ' - ' || DESCRICAO_ESPECIE AS COD_ESPECIE,
    NRO_TITULO || ' - Parc: ' || NRO_PARCELA AS TITULO,
    NRO_EMPRESA AS FILIAL,
    SEQ_PESSOA,
    FORNECEDOR,
    DTA_INCLUSAO_TIT AS DTA_INCLUSAO,
    DTA_INCLUSAO AS DTA_INCLUSAO_PGTO,
    TO_CHAR(DTA_INCLUSAO_TIT, 'DD/MM/YYYY') AS DTA_INCLUSAO_FMT,
    DTA_PROGRAMACAO AS DTA_PROGRAMADA,
    TO_CHAR(DTA_PROGRAMACAO, 'DD/MM/YYYY') AS DTA_PROGRAMADA_FMT,
    VLR_PAGAR AS VLR_ORIGINAL,
    VLR_JUROS + VLR_MULTA AS JUROS_MULTA,
    CASE
        WHEN NRO_EMPRESA IN (1, 2, 3, 4) THEN 'EMPRESA_A'
        WHEN NRO_EMPRESA IN (5) THEN 'EMPRESA_B'
        ELSE 'EMPRESA_C'
    END AS EMPRESA,
    DTA_HORA_ALTERACAO,
    TO_CHAR(DTA_HORA_ALTERACAO, 'DD/MM/YYYY HH24:MI') AS DTA_HORA_ALTERACAO_FMT,
    CASE
        WHEN COD_ESPECIE IN ('ESP01', 'ESP02', 'ESP03', 'ESP04', 'ESP05') THEN '0'
        ELSE '1'
    END AS EXC_ESPECIES,
    ABERTO_QUITADO AS STATUS,
    DTA_EMISSAO,
    TO_CHAR(DTA_EMISSAO, 'DD/MM/YYYY') AS DTA_EMISSAO_FMT,
    CASE
        WHEN COD_ESPECIE IN ('IMP01','IMP02','IMP03','IMP04','IMP05','IMP06','IMP07','IMP08','IMP09','IMP10','IMP11','IMP12') THEN
            ABS(TRUNC(DTA_PROGRAMACAO) - TRUNC(DTA_EMISSAO))
        WHEN QTD_PARCELA > 1 AND ORIGEM_DOC = 'INTE' THEN
            ABS(TRUNC(DTA_PROGRAMACAO) - TRUNC(DTA_EMISSAO))
        ELSE
            COALESCE(
                MEDIA_DIAS_ORIGINAIS,
                ABS(TRUNC(DTA_PROGRAMACAO) - TRUNC(COALESCE(DTA_EMISSAO_ORIGINAL, DTA_EMISSAO)))
            )
    END AS DIAS_PAGAMENTO,
    NOME_REDUZIDO_EMPRESA,
    CONTA_CORRENTE,
    CASE
        WHEN FORMA_PAGTO = 'EL' THEN 'Remessa'
        WHEN HISTORICO IS NOT NULL THEN 'Pagamento Manual'
        WHEN FORMA_PAGTO = 'OB' AND COD_ESPECIE IN ('SAL01','SAL02','SAL03','SAL04','SAL05') THEN 'Remessa Folha'
        ELSE 'Aut. Debito em Conta'
    END AS TIPO_PAGTO,
    CASE
        WHEN FORMA_PAGTO = 'EL' THEN 'Eletronico'
        WHEN FORMA_PAGTO = 'OB' THEN 'Aut. Debito em Conta'
        WHEN FORMA_PAGTO = 'DI' THEN 'Dinheiro'
        WHEN FORMA_PAGTO = 'CP' THEN 'Cheque Proprio'
    END AS FORMA_PAGAMENTO,
    ROUND(AVG(ABS(DTA_PROGRAMACAO - DTA_EMISSAO)) OVER ()) AS MEDIA_GERAL_DIAS,
    DTA_INCLUSAO AS DATA_INCL_PROG,
    CASE
        WHEN FORMA_PAGTO = 'OB' AND APP_ORIGEM <> 'IntOrcamento' AND NRO_AUT_ELETRONICA IS NOT NULL THEN NULL
        WHEN FORMA_PAGTO = 'OB' AND APP_ORIGEM = 'IntOrcamento' AND NRO_AUT_ELETRONICA IS NULL THEN NVL(HISTORICO, NRO_TITULO || ' - ' || NRO_EMPRESA)
        WHEN FORMA_PAGTO = 'OB' AND APP_ORIGEM IS NULL AND NRO_AUT_ELETRONICA IS NULL THEN NVL(HISTORICO, NRO_TITULO || ' - ' || NRO_EMPRESA)
        WHEN FORMA_PAGTO = 'EL' THEN NULL
        ELSE NULL
    END AS HISTORICO
FROM DADOS_ENRIQUECIDOS
WHERE RN = 1
ORDER BY
    CASE
        WHEN COMPRADOR = '*DESPESA*' THEN 'ZZZZZZZZZZ'
        ELSE COMPRADOR
    END,
    COD_ESPECIE,
    DTA_PROGRAMACAO,
    FORNECEDOR,
    NRO_TITULO || NRO_PARCELA
;
