/*
  View: PASV_TITULOS_EM_ABERTO_COMPRADOR
  Autor: Carlos Ribeiro
  Descrição: Versão original da view utilizada para análise de títulos em aberto.
  Data de criação: 2024
*/



CREATE OR REPLACE VIEW PASV_TITULOS_EM_ABERTO_COMPRADOR AS
SELECT "RN",
       "COMPRADOR",
       "CODESPECIE",
       "TITULO",
       "FILIAL",
       "SEQPESSOA",
       "FORNECEDOR",
       "DTAINCLUSAO",
       "DTAINCLUSAOPGTO",
       "DTAINCLUSAOFMT",
       "DTAPROGRAMADA",
       "DTAPROGRAMADAFMT",
       "VLRORIGINAL",
       "JUROS_MULTA",
       "EMPRESA",
       "DTAHORAALTERACAO",
       "DTAHORAALTERACAOFMT",
       "EXC_ESPECIES",
       "ABERTOQUITADO",
       "DTAEMISSAO",
       "DTAEMISSAOFMT",
       "DIAS_PAGAMENTO",
       "NOMEREDUZIDO_EMPRESA",
       "CONTA_CORRENTE",
       "TIPO_PAGTO",
       "FORMA_PAGAMENTO",
       "MEDIA_GERAL_DIAS",
       "DATAINCLPROG",
       "HISTORICO"
FROM (
    SELECT
    T0.SEQTITULO,
        ROW_NUMBER() OVER (PARTITION BY T0.SEQTITULO
                           ORDER BY T3.COMPRADOR,
                                    T1.CODESPECIE,
                                    T0.DTAPROGRAMACAO,
                                    T4.NOMERAZAO,
                                    T1.NROTITULO || T1.NROPARCELA) AS RN,

NVL(
    T3.COMPRADOR,
    CASE
        -- Caso FRETE: busca comprador pelos titulos do mesmo NROPROCESSO
        WHEN T1.CODESPECIE = 'FRETE' THEN NVL((
            SELECT MAX(C_SUB.COMPRADOR)
            FROM FI_TITOPERACAO OP_SUB
            JOIN FI_TITCOMPRADOR TC_SUB
                ON TC_SUB.SEQTITULO = OP_SUB.SEQTITULO
            JOIN MAX_COMPRADOR C_SUB
                ON C_SUB.SEQCOMPRADOR = TC_SUB.SEQCOMPRADOR
            WHERE OP_SUB.NROPROCESSO = (
                SELECT OP.NROPROCESSO
                FROM FI_TITOPERACAO OP
                WHERE OP.SEQTITULO = T1.SEQTITULO
                  AND ROWNUM = 1
            )
            AND OP_SUB.SEQTITULO != T1.SEQTITULO
        ), '*DESPESA*')

        -- Caso seja uma parcela sem comprador: busca o titulo original
        WHEN EXISTS (
            SELECT 1
            FROM FI_TITULO T_ORIG
            WHERE T_ORIG.NROTITULO  = T1.NROTITULO
              AND T_ORIG.NROEMPRESA = T1.NROEMPRESA
              AND T_ORIG.SEQPESSOA  = T1.SEQPESSOA
              AND T_ORIG.SITUACAO   = 'X'
              AND T_ORIG.ORIGEMDOC  = 'INTE'
              AND T_ORIG.SEQTITULO <> T1.SEQTITULO
        )
        AND NOT EXISTS (
            SELECT 1
            FROM FI_TITCOMPRADOR TC
            WHERE TC.SEQTITULO = T1.SEQTITULO
        ) THEN NVL((
            SELECT MAX(C_SUB.COMPRADOR)
            FROM (
                SELECT TIT_ORIG.SEQTITULO
                FROM FI_TITULO TIT_ORIG
                WHERE TIT_ORIG.NROTITULO  = T1.NROTITULO
                  AND TIT_ORIG.NROEMPRESA = T1.NROEMPRESA
                  AND TIT_ORIG.SEQPESSOA  = T1.SEQPESSOA
                  AND TIT_ORIG.SITUACAO   = 'X'
                  AND TIT_ORIG.ORIGEMDOC  = 'INTE'
                  AND TIT_ORIG.SEQTITULO <> T1.SEQTITULO
                  AND TIT_ORIG.NROPARCELA = (
                      SELECT MIN(T2.NROPARCELA)
                      FROM FI_TITULO T2
                      WHERE T2.NROTITULO  = T1.NROTITULO
                        AND T2.NROEMPRESA = T1.NROEMPRESA
                        AND T2.SEQPESSOA  = T1.SEQPESSOA
                        AND T2.SITUACAO   = 'X'
                        AND T2.ORIGEMDOC  = 'INTE'
                  )
            ) TIT_SEL
            JOIN FI_TITCOMPRADOR TC_SUB
                ON TC_SUB.SEQTITULO = TIT_SEL.SEQTITULO
            JOIN MAX_COMPRADOR C_SUB
                ON C_SUB.SEQCOMPRADOR = TC_SUB.SEQCOMPRADOR
        ), '*DESPESA*')

        -- Fallback
        ELSE '*DESPESA*'
    END
) AS COMPRADOR,
        T1.CODESPECIE || ' - ' || T5.DESCRICAO CODESPECIE,
        T1.NROTITULO || ' - Parc: ' || T1.NROPARCELA TITULO,
        T1.NROEMPRESA AS FILIAL,
        T4.SEQPESSOA,
        T4.NOMERAZAO FORNECEDOR,
        T1.DTAINCLUSAO,
        T0.DTAINCLUSAO AS DTAINCLUSAOPGTO, ---------------------------
        TO_CHAR(T1.DTAINCLUSAO, 'DD/MM/YYYY') DTAINCLUSAOFMT,
        T0.DTAPROGRAMACAO DTAPROGRAMADA,
        TO_CHAR(T0.DTAPROGRAMACAO, 'DD/MM/YYYY') DTAPROGRAMADAFMT,
        T0.VLRPAGAR AS VLRORIGINAL,
        T0.VLRJUROS + t0.vlrmulta AS JUROS_MULTA,

        CASE
            WHEN T1.NROEMPRESA IN (30, 31, 32, 33) THEN 'TECH'
            WHEN T1.NROEMPRESA IN (20) THEN 'INSTALA'
            ELSE 'PASSALACQUA'
        END EMPRESA,

        T0.DTAHORALTERACAO DTAHORAALTERACAO,
        TO_CHAR(T0.DTAHORALTERACAO, 'DD/MM/YYYY HH24:MI') DTAHORAALTERACAOFMT,
        CASE
            WHEN T1.CODESPECIE IN ('DEVPAG', 'NOCRAC', 'NOCRIM', 'NOTACR', 'NOTCRB') THEN '0'
            ELSE '1'
        END EXC_ESPECIES,
        T1.ABERTOQUITADO,
        T1.DTAEMISSAO,
        TO_CHAR(T1.DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAOFMT,

CASE
    -- Calculo especifico para receita federal
    WHEN T1.CODESPECIE IN ('ISS','IRPJ','ICMSST','IPTU','ICMS','IRSERV','CSLRET','DIFAL','IRAUTO','IRASSA','PROTEG','INSS') THEN
        ABS(TRUNC(T0.DTAPROGRAMACAO) - TRUNC(T1.DTAEMISSAO))

    -- Parcelados 
    WHEN T1.QTDPARCELA > 1 AND T1.ORIGEMDOC = 'INTE' THEN
        ABS(TRUNC(T0.DTAPROGRAMACAO) - TRUNC(T1.DTAEMISSAO))

    -- Media simples dos titulos originais ou fallback
    ELSE
        COALESCE(
            T_MEDIA_ORIG.MEDIA_DIAS_ORIGINAIS,
            ABS(TRUNC(T0.DTAPROGRAMACAO) - TRUNC(COALESCE(T_ORIG.DTAEMISSAO_ORIGINAL, T1.DTAEMISSAO)))
        )
END AS DIAS_PAGAMENTO,



        T6.NOMEREDUZIDO NOMEREDUZIDO_EMPRESA,
        T9.DESCRICAO AS CONTA_CORRENTE,

        CASE
            WHEN T0.FORMAPAGTO = 'EL' THEN 'Remessa'
            WHEN T0.HISTORICO IS NOT NULL THEN 'Pagamento Manual'
            WHEN T0.FORMAPAGTO = 'OB' AND T1.CODESPECIE IN ('ADIFER','ADIRES','ADISAL','ADI13','SALARI') THEN 'Remessa Folha'
            ELSE 'Aut. Debito em Conta'
        END AS TIPO_PAGTO,

        CASE
            WHEN T0.FORMAPAGTO = 'EL' THEN 'Eletronico'
            WHEN T0.FORMAPAGTO = 'OB' THEN 'Aut. Debito em Conta'
            WHEN T0.FORMAPAGTO = 'DI' THEN 'Dinheiro'
            WHEN T0.FORMAPAGTO = 'CP' THEN 'Cheque Proprio'
        END AS FORMA_PAGAMENTO,

        ROUND(AVG(ABS(T0.DTAPROGRAMACAO - T1.DTAEMISSAO)) OVER ()) AS MEDIA_GERAL_DIAS,
        T0.DTAINCLUSAO AS DATAINCLPROG,
                CASE
            WHEN T0.FORMAPAGTO = 'OB' AND T1.APPORIGEM <> 'IntOrcamento' and T1.NROAUTELETRONICA IS NOT NULL THEN NULL
            WHEN T0.FORMAPAGTO = 'OB' AND T1.APPORIGEM = 'IntOrcamento' and T1.NROAUTELETRONICA IS NULL THEN NVL( t0.historico ,T1.NROTITULO || ' - ' || T1.NROEMPRESA)
            WHEN T0.FORMAPAGTO = 'OB' AND T1.APPORIGEM  IS NULL and T1.NROAUTELETRONICA IS NULL THEN NVL( t0.historico ,T1.NROTITULO || ' - ' || T1.NROEMPRESA)
            WHEN T0.FORMAPAGTO = 'EL'  THEN NULL
            ELSE NULL
        END AS HISTORICO

    FROM
        FI_PROGPAGAMENTO T0
        INNER JOIN FI_TITULO T1 ON T1.SEQTITULO = T0.SEQTITULO
        LEFT JOIN (
    SELECT TC_FILTRADO.SEQTITULO, C.COMPRADOR
    FROM (
        SELECT
            TC.SEQTITULO,
            TC.SEQCOMPRADOR,
            T.VLRORIGINAL,
            TC.VALOR,
            ROW_NUMBER() OVER (
                PARTITION BY TC.SEQTITULO
                ORDER BY
                    CASE WHEN TC.VALOR = T.VLRORIGINAL THEN 0 ELSE 1 END,
                    TC.VALOR DESC
            ) AS RN
        FROM FI_TITCOMPRADOR TC
        JOIN FI_TITULO T ON T.SEQTITULO = TC.SEQTITULO
    ) TC_FILTRADO
    JOIN MAX_COMPRADOR C ON C.SEQCOMPRADOR = TC_FILTRADO.SEQCOMPRADOR
    WHERE TC_FILTRADO.RN = 1
) T3 ON T3.SEQTITULO = T1.SEQTITULO

LEFT JOIN (
    SELECT
        NROTITULO, NROEMPRESA, CODESPECIE, SEQPESSOA,
        MIN(DTAEMISSAO) AS DTAEMISSAO_ORIGINAL
    FROM FI_TITULO
    WHERE ORIGEMDOC = 'INTE'  -- Apenas titulos originais
    GROUP BY NROTITULO, NROEMPRESA, CODESPECIE, SEQPESSOA
) T_ORIG ON T_ORIG.NROTITULO = T1.NROTITULO
        AND T_ORIG.NROEMPRESA = T1.NROEMPRESA
        AND T_ORIG.CODESPECIE = T1.CODESPECIE
        AND T_ORIG.SEQPESSOA = T1.SEQPESSOA

LEFT JOIN (
    SELECT
        T_AGR.NROTITULO,
        T_AGR.NROEMPRESA,
        T_AGR.SEQPESSOA,
        T_AGR.CODESPECIE,
        AVG(ABS(PP.DTAPROGRAMACAO - COALESCE(T_ORIG_SUB.DTAEMISSAO_ORIGINAL, T_ORIG_SIMPLE.DTAEMISSAO))) AS MEDIA_DIAS_ORIGINAIS
    FROM FI_TITULO T_AGR
    INNER JOIN FI_TITULO T_ORIG_SIMPLE ON
        T_ORIG_SIMPLE.NROTITULO = T_AGR.NROTITULO
        AND T_ORIG_SIMPLE.NROEMPRESA = T_AGR.NROEMPRESA
        AND T_ORIG_SIMPLE.SEQPESSOA = T_AGR.SEQPESSOA
        AND T_ORIG_SIMPLE.ORIGEMDOC = 'INTE'
        AND T_ORIG_SIMPLE.SITUACAO = 'X'
        AND T_ORIG_SIMPLE.CODESPECIE = T_AGR.CODESPECIE
        AND T_ORIG_SIMPLE.SEQTITULO <> T_AGR.SEQTITULO
        AND (T_ORIG_SIMPLE.QTDPARCELA IS NULL OR T_ORIG_SIMPLE.QTDPARCELA <= 1)  
    LEFT JOIN FI_PROGPAGAMENTO PP ON PP.SEQTITULO = T_ORIG_SIMPLE.SEQTITULO
    LEFT JOIN (
        SELECT
            NROTITULO, NROEMPRESA, CODESPECIE, SEQPESSOA,
            MIN(DTAEMISSAO) AS DTAEMISSAO_ORIGINAL
        FROM FI_TITULO
        WHERE ORIGEMDOC = 'INTE'
        GROUP BY NROTITULO, NROEMPRESA, CODESPECIE, SEQPESSOA
    ) T_ORIG_SUB ON
        T_ORIG_SUB.NROTITULO = T_ORIG_SIMPLE.NROTITULO
        AND T_ORIG_SUB.NROEMPRESA = T_ORIG_SIMPLE.NROEMPRESA
        AND T_ORIG_SUB.CODESPECIE = T_ORIG_SIMPLE.CODESPECIE
        AND T_ORIG_SUB.SEQPESSOA = T_ORIG_SIMPLE.SEQPESSOA
    WHERE T_AGR.SITUACAO <> 'C'
    GROUP BY T_AGR.NROTITULO, T_AGR.NROEMPRESA, T_AGR.CODESPECIE ,T_AGR.SEQPESSOA
) T_MEDIA_ORIG ON
    T_MEDIA_ORIG.NROTITULO = T1.NROTITULO
    AND T_MEDIA_ORIG.NROEMPRESA = T1.NROEMPRESA
    AND T_MEDIA_ORIG.SEQPESSOA = T1.SEQPESSOA
    AND T_MEDIA_ORIG.CODESPECIE = T1.CODESPECIE



        INNER JOIN GE_PESSOA T4 ON T4.SEQPESSOA = T1.SEQPESSOA
        LEFT JOIN FI_ESPECIE T5 ON T5.CODESPECIE = T1.CODESPECIE AND T1.NROEMPRESAMAE = T5.NROEMPRESAMAE
        INNER JOIN MAX_EMPRESA T6 ON T6.NROEMPRESA = T1.NROEMPRESA
        INNER JOIN FI_CTACORRENTE T9 ON T9.SEQCTACORRENTE = T0.SEQCTACORRENTE
        INNER JOIN FI_COMPLTITULO T8 ON T8.SEQTITULO = T0.SEQTITULO

    WHERE
        T1.OBRIGDIREITO = 'O' --OK
        AND T1.SITUACAO <> 'C' --OK
        AND T1.DTAEMISSAO > TO_DATE('01-JAN-2020', 'DD-MON-YYYY')
        AND (T0.SITUACAO <> 'C' OR T0.SITUACAO IS NULL)
        --AND t1.dtaprogramada = '18-jun-2025'

       and T0.SEQCTACORRENTE IN (30735,31, 21779, 30215, 30216, 8545, 35903, 30368, 25142, 22169,31815,28522 ,663, 25, 24, 23, 28, 12863, 42, 221, 33116, 33118, 30367, 28495, 30218, 27, 32)
)
WHERE RN = 1
ORDER BY
    CASE
        WHEN COMPRADOR = '*DESPESA*' THEN 'ZZZZZZZZZZ'
        ELSE COMPRADOR
    END,
    CODESPECIE,
    DTAPROGRAMADA,
    FORNECEDOR,
    TITULO
;
